!> Initialize ensemble
!!
!! User-supplied call-back routine for PDAF.
!!
!! Used in all DA methods.
!!
!! The routine is called by PDAF when the DA is initialized.
!! It has to initialize an ensemble of dim_ens states.
!!
!! The routine is called by all filter processes and 
!! initializes the ensemble for the process-local domain.
!!
!! Implementation for the 2D online example with parallelization.
!! Here, the ensemble is either directly read from model files
!! or it can be generated by 2nd order exact sampling from a
!! covariance matrix.
!!
!! __Revision history:__
!! * 2026-02 - Lars Nerger - Initial code for advanced tutorial revising tutorial case
!! * Later revisions - see repository log
!!
subroutine init_ens_pdaf(filtertype, dim_p, dim_ens, state_p, Uinv, &
     ens_p, flag)

  use netcdf
  use PDAF, &                     ! PDAF
       only: PDAF_sampleens
  use assimilation_pdaf_mod, &    ! Assimilation varibles
       only: type_ens_init, file_covar
  use model_pdaf_mod, &           ! Model variables
       only: nx, ny, nx_p
  use parallel_pdaf_mod, &        ! Assimilation parallelization variables
       only: mype_filter
  use statevector_pdaf_mod, &     ! State vector variables
       only: id, sfields, n_fields
  use io_pdaf_mod, &              ! File operations
       only: read_pdaf, read_covar_pdaf

  implicit none

! *** Arguments ***
  integer, intent(in) :: filtertype                !< Type of filter to initialize
  integer, intent(in) :: dim_p                     !< process-local state dimension
  integer, intent(in) :: dim_ens                   !< Size of ensemble
  real, intent(inout) :: state_p(dim_p)            !< process-local model state
  !< (It is not necessary to initialize the array 'state_p' for ensemble filters.
  !< It is available here only for convenience and can be used freely.)
  real, intent(inout) :: Uinv(dim_ens-1,dim_ens-1) !< Array not referenced for ensemble filters
  real, intent(out)   :: ens_p(dim_p, dim_ens)     !< process-local state ensemble
  integer, intent(inout) :: flag                   !< PDAF status flag

! *** local variables ***
  integer :: i, j, s, fid, member     ! Counters
  character(len=4) :: ensstr          ! String for ensemble member
  character(len=100) :: filename      ! Name of input file
  real, allocatable :: field_p(:,:)   ! process-local model field
  real, allocatable :: eofs(:,:)      ! matrix of eigenvectors V 
  real, allocatable :: svals(:)       ! singular values


! **********************
! *** INITIALIZATION ***
! **********************

  ! *** Generate full ensemble on filter-Process 0 ***
  if (mype_filter==0) then
     write (*, '(/a, 5x, a)') 'model-PDAF', 'Initialize state ensemble'
     if (type_ens_init==1) then
        write (*, '(a, 5x, a)') 'model-PDAF', '--- read ensemble from files'
     else
        write (*, '(a, 5x, a)') 'model-PDAF', &
             '--- generate ensemble from covariance matrix with 2nd-order exact sampling'
     end if
     write (*, '(a, 5x, a, i5)') 'model-PDAF', '--- Ensemble size:  ', dim_ens
  end if


! ********************************
! *** Initialize ensemble      ***
! ********************************

  inittype: if (type_ens_init==1) then

     ! *************************************************
     ! *** Initialize ensemble reading model outputs ***
     ! *************************************************

     ! allocate memory for temporary fields
     allocate(field_p(ny, nx_p))

     if (mype_filter==0) &
          write (*,'(a, 5x, a)') 'model-PDAF', '--- read ensemble files'

     do member = 1, dim_ens
        if (member<10) then
           write (ensstr, '(i1)') member
        elseif (member<100) then
           write (ensstr, '(i2)') member
        elseif (member<1000) then
           write (ensstr, '(i3)') member
        end if

        do fid = 1, n_fields

           ! Read ensemble files
           filename = '../inputs_2fields/ens'//trim(sfields(fid)%fname)//'_'//trim(ensstr)//'.nc'
           call read_pdaf(filename, field_p)

           ! +++ Note on counter s:
           ! +++ Using the counter s looks primitive, but it
           ! +++ makes the code fail-save because it avoids
           ! +++ index calculations involving nx_p or ny.

           ! Initialize process-local part of ensemble
           s = sfields(fid)%off
           do j = 1, nx_p
              do i = 1, ny
                 s = s + 1
                 ens_p(s, member) = field_p(i, j)
              end do
           end do
        end do
     end do

     deallocate(field_p)

  else inittype

     ! **************************************************
     ! *** Initialize ensemble from covariance matrix ***
     ! **************************************************

     ! allocate temporary arrays
     allocate(eofs(dim_p, dim_ens-1))
     allocate(svals(dim_ens-1))

     ! *** Read initial state and covar matrix ***

     if (mype_filter==0) &
          write(*,'(a,5x,a,a)') 'model-PDAF', '--- Read covariance information from ', trim(file_covar)

     call read_covar_pdaf(file_covar, dim_ens, eofs, svals, state_p)


     ! *** Generate ensemble of model states ***

     if (mype_filter==0) &
          write (*,'(a, 5x, a)') 'model-PDAF', '--- generate state ensemble'
     
     ! Use PDAF routine for second-order exact sampling
     call PDAF_SampleEns(dim_p, dim_ens, eofs, svals, state_p, ens_p, 1, flag)

     deallocate(eofs, svals)

  end if inittype

end subroutine init_ens_pdaf
