!> Module providing routines for writing and reading
!! synthetic observations that are generated by PDAF. 
!! For the files the netCDF file format is used. 
!! Usually can can use these routines without modifications.
!!
!! __Revision history:__
!! * 2019-01 - Lars Nerger - Initial code
!! * Later revisions - see svn log
!!
module synobs_pdaf_mod

contains
!-----------------------------------------------------------
!>  Initialize observation file
!!
!! This routine initializes the file holding synthetic 
!! observations generated by PDAF.
!!
!! The routine should only be called by a single filter
!! process of only one file is generated. If a separate file
!! for each process should be generated, each process has to
!! call this routine.
!!
  subroutine init_file_syn_obs(dim_obs_max, file_obs, screen)

    use netcdf        ! Netcdf binary format

    implicit none

! *** Arguments ***
    integer, intent(in) :: dim_obs_max       !< maximum dimension of full observation vector
    character(len=*), intent(in) :: file_obs !< Name of observation file
    integer, intent(in) :: screen            !< Whether to print output


! *** Local variables ***
    integer :: i, s                               ! Counters
    integer :: dimid_iter, dimid_one, dimid_obs   ! IDs for dimensions
    integer :: id_time, id_obs, id_var            ! IDs for variables
    integer :: dimids(2)                          ! Array of IDs
    integer :: stat(100)                          ! Status array
    integer :: fileid                             ! netcdf file id
    character(len=150) :: attstr                  ! String for attribute


    ! Print name file observation file
    if (screen>0) then
       write (*,'(/5x,a,a)') 'GENOBS: Initialize file for synthetic observations: ',trim(file_obs)
    end if

! *** Initialize file

  call nfcheck( NF90_CREATE(file_obs, 0, fileid))

  attstr  = 'Synthetic observations'
  call nfcheck( NF90_PUT_ATT(fileid, NF90_GLOBAL, 'title', trim(attstr))) 

  ! Define dimensions
  call nfcheck( NF90_DEF_DIM(fileid, 'dim_obs_max', dim_obs_max, dimid_obs))
  call nfcheck( NF90_DEF_DIM(fileid, 'one',  1, dimid_one))
  call nfcheck( NF90_DEF_DIM(fileid, 'steps',  NF90_UNLIMITED, dimid_iter))

  ! Define variables
  call nfcheck( NF90_DEF_VAR(fileid, 'time', NF90_DOUBLE, dimid_iter, Id_time)) 

  dimids(1) = DimId_obs
  dimids(2) = dimid_iter

  call nfcheck( NF90_DEF_VAR(fileid, 'obs', NF90_DOUBLE, dimids, Id_obs))
  call nfcheck( NF90_DEF_VAR(fileid, 'dim_obs_f', NF90_INT, dimids(2), Id_var))
  call nfcheck( NF90_ENDDEF(fileid))

  ! Close file
  call nfcheck( NF90_CLOSE(fileid))

end subroutine init_file_syn_obs

! ---------------------------------------------------
!> Write vector of synthetic observations to file
!!
!! This routine writes observations into a netcdf file
!!
!! The routine should only be called by a single filter
!! process if a single file is used (usually holding
!! all available observations). If separate files
!! for difference processes are used, each of these
!! processes needs to call the routine.
!!
!! __Revision history:__
!! * 2019-01 - Lars Nerger - Initial code
!! * Later revisions - see svn log
!!
subroutine write_syn_obs(step, file_obs, dim_obs_f, observation_f, screen)

  use netcdf        ! Netcdf binary format

  implicit none

! *** Arguments ***
  integer, intent(in) :: step        !< Currrent time step
  integer, intent(in) :: dim_obs_f   !< Dimension of full observation vector
  real, intent(in)    :: observation_f(dim_obs_f) !< Full observation vector
  character(len=*)    :: file_obs    !< Name of observation file
  integer, intent(in) :: screen      !< Whether to print output

! *** Local variables ***
  integer :: i                            ! Counters
  integer, save :: iter=0                 ! file iteration counter
  integer :: fileid                       ! netcdf-ID of file
  integer :: id_time, id_obs, id_dimobsf  ! IDs for dimensions
  integer :: id_dimobsmax                 ! ID for dimension variable
  integer :: stat(100)                    ! status flag
  integer :: countv(2), startv(2)         ! index arrays for writing

  integer :: dim_obs_max   ! maximum observation dimension in file
  integer :: dim_obs_store ! size of observation vector to be stored, min(dim_obs_max, dim_obs_f)


  
! ************************************************
! *** Configuration                            ***
! ************************************************

  ! Increment file position counter
  iter = iter + 1

  ! Print name file observation file
  if (screen>0) then
     write (*,'(5x,a,i7,a,a)') 'GENOBS: Write synthetic observations at index ', iter, &
          ' to file: ',trim(file_obs)
  end if

! ***********************************************
! *** Write observational information to file ***
! ***********************************************

  ! Open file
  call nfcheck( NF90_OPEN(trim(file_obs), NF90_WRITE, fileid))

  ! Read maximum number of observations
  call nfcheck( NF90_INQ_DIMID(fileid, 'dim_obs_max', id_dimobsmax))
  call nfcheck( NF90_Inquire_dimension(fileid, id_dimobsmax, len=dim_obs_max))

  ! Write time
  call nfcheck( NF90_INQ_VARID(fileid, 'time', id_time))

  startv(1) = iter
  countv(1) = 1
  call nfcheck( NF90_PUT_VAR(fileid, id_time, real(step), start=startv(1:1)))

  ! Write dim_obs_f
  call nfcheck( NF90_INQ_VARID(fileid, 'dim_obs_f', id_dimobsf))

  if (dim_obs_f<= dim_obs_max) then
     dim_obs_store = dim_obs_f
  else
     dim_obs_store = dim_obs_max
     write (*,*) 'WARNING: Truncating observations to maximum observation dimension in file'
  end if
  startv(1) = iter
  countv(1) = 1
  call nfcheck( NF90_PUT_VAR(fileid, id_dimobsf, dim_obs_store, start=startv(1:1)))

  ! Write vector of observations
  call nfcheck( NF90_INQ_VARID(fileid, 'obs', id_obs))

  startv(2) = iter
  countv(2) = 1
  startv(1) = 1
  countv(1) = dim_obs_store
  call nfcheck( NF90_PUT_VAR(fileid, id_obs, observation_f, start=startv))

  ! Close files
  call nfcheck( NF90_CLOSE(fileid))
  
end subroutine write_syn_obs
! ---------------------------------------------------
!> Read vector of synthetic observations from file
!!
!! This routine writes observations into a netcdf file
!!
!! The routine should only be called by a single filter
!! process if a single file is used (usually holding
!! all available observations). If separate files
!! for difference processes are used, each of these
!! processes needs to call the routine.
!!
!! __Revision history:__
!! * 2019-01 - Lars Nerger - Initial code
!! *Later revisions - see svn log
!!
subroutine read_syn_obs(file_obs, dim_obs_f, observation_f, step, screen)

  use netcdf        ! Netcdf binary format

  implicit none

! *** Arguments ***
  integer, intent(in) :: dim_obs_f   !< Dimension of full observation vector
  real, intent(out)   :: observation_f(dim_obs_f) !< Full observation vector
  character(len=*)    :: file_obs    !< Name of observation file
  integer, intent(in) :: step        !< File time step to read
  integer, intent(in) :: screen      !< Whether to print output

! *** Local variables ***
  integer :: i, s                         ! Counters
  integer, save :: iter=0                 ! file iteration counter
  integer :: fileid                       ! netcdf-ID of file
  integer :: id_obs                       ! IDs for dimensions
  integer :: id_dimobsmax                 ! ID for dimension variable
  integer :: stat(100)                    ! status flag
  integer :: countv(2), startv(2)         ! index arrays for writing

  integer :: dim_obs_max   ! maximum observation dimension in file
  integer :: dim_obs_store ! size of observation vector to be stored, min(dim_obs_max, dim_obs_f)


  
! ************************************************
! *** Configuration                            ***
! ************************************************

  ! Print name file observation file
  if (screen>0) then
     write (*,'(5x,a,i7,a,a)') 'Read synthetic observations at step ', step, &
          ' from file: ',trim(file_obs)
  end if

! ***********************************************
! *** Write observational information to file ***
! ***********************************************

  ! Open file
  call nfcheck( NF90_OPEN(trim(file_obs), NF90_WRITE, fileid))

  ! Read maximum number of observations
  call nfcheck( NF90_INQ_DIMID(fileid, 'dim_obs_max', id_dimobsmax))
  call nfcheck( NF90_Inquire_dimension(fileid, id_dimobsmax, len=dim_obs_max))

  if (dim_obs_f<= dim_obs_max) then
     dim_obs_store = dim_obs_f
  else
     dim_obs_store = dim_obs_max
     write (*,*) 'WARNING: Truncating observations to maximum observation dimension in file'
  end if

  ! Write vector of observations
  call nfcheck( NF90_INQ_VARID(fileid, 'obs', id_obs))

  startv(2) = step
  countv(2) = 1
  startv(1) = 1
  countv(1) = dim_obs_store
  call nfcheck( NF90_GET_VAR(fileid, id_obs, observation_f, start=startv, count=countv))


! *****************
! *** Clean up  ***
! *****************

  ! Close files
  call nfcheck( NF90_CLOSE(fileid))
  
end subroutine read_syn_obs


!-------------------------------------------------------------------------------
!> Check status of netcdf operation
!!
  subroutine nfcheck(status)

    use netcdf
    use parallel_pdaf_mod, &
         only: abort_parallel

! *** Aruments ***
    integer, intent ( in) :: status   ! Reading status

    if(status /= nf90_noerr) then
       print *, trim(nf90_strerror(status))
       call abort_parallel()
    end if

  end subroutine nfcheck

end module synobs_pdaf_mod
