!> Initialize ensemble
!!
!! User-supplied call-back routine for PDAF.
!!
!! Used in all DA methods.
!!
!! The routine is called by PDAF when the DA is initialized.
!! It has to initialize an ensemble of dim_ens states.
!!
!! The routine is called by all filter processes and 
!! initializes the ensemble for the process-local domain.
!!
!! Implementation for the 2D online example with parallelization.
!! Here, the ensemble is either directly read from model files
!! or it can be generated by 2nd order exact sampling from a
!! covariance matrix.
!!
!! __Revision history:__
!! * 2026-02 - Lars Nerger - Initial code for advanced tutorial revising tutorial case
!! * Later revisions - see repository log
!!
subroutine init_ens_pdaf_offline(filtertype, dim_p, dim_ens, state_p, Uinv, &
     ens_p, flag)

  use netcdf
  use pdaf, &
       only: PDAF_sampleens
  use assimilation_pdaf_mod, &
       only: type_ens_init, file_covar
  use model_pdaf_mod, &           ! Model variables
       only: nx, ny, nx_p
  use parallel_pdaf_mod, &        ! Assimilation parallelization variables
       only: mype_filter, mype_model, abort_parallel
  use statevector_pdaf_mod, &     ! State vector variables
       only: id, sfields, n_fields
  use output_pdaf_mod, &          ! File operations
       only: nfcheck

  implicit none

! *** Arguments ***
  integer, intent(in) :: filtertype                !< Type of filter to initialize
  integer, intent(in) :: dim_p                     !< process-local state dimension
  integer, intent(in) :: dim_ens                   !< Size of ensemble
  real, intent(inout) :: state_p(dim_p)            !< process-local model state
  !< (It is not necessary to initialize the array 'state_p' for ensemble filters.
  !< It is available here only for convenience and can be used freely.)
  real, intent(inout) :: Uinv(dim_ens-1,dim_ens-1) !< Array not referenced for ensemble filters
  real, intent(out)   :: ens_p(dim_p, dim_ens)     !< process-local state ensemble
  integer, intent(inout) :: flag                   !< PDAF status flag

! *** local variables ***
  integer :: i, j, s, fid, member     ! Counters
  integer :: rank_file                ! Number of EOFs stored in covariance file
  integer :: stat(50)                 ! Array for status flag
  integer :: fileid                   ! ID for NetCDF file
  integer :: id_svals, id_eofs        ! IDs for fields
  integer :: id_state                 ! ID for field
  integer :: id_dim                   ! ID for dimension
  integer :: countv(3), startv(3)     ! Vectors for NC operations
  integer :: off_nx                   ! Offset of local grid in global domain in x-direction
  character(len=4) :: ensstr          ! String for ensemble member
  real, allocatable :: field(:,:)     ! global model field
  real, allocatable :: eofs(:,:)      ! matrix of eigenvectors V 
  real, allocatable :: svals(:)       ! singular values


! **********************
! *** INITIALIZATION ***
! **********************

  ! *** Generate full ensemble on filter-Process 0 ***
  if (mype_filter==0) then
     write (*, '(/a, 5x, a)') 'model-PDAF', 'Initialize state ensemble'
     if (type_ens_init==1) then
        write (*, '(a, 5x, a)') 'model-PDAF', '--- read ensemble from files'
     else
        write (*, '(a, 5x, a)') 'model-PDAF', &
             '--- generate ensemble from covariance matrix with 2nd-order exact sampling'
     end if
     write (*, '(a, 5x, a, i5)') 'model-PDAF', '--- Ensemble size:  ', dim_ens
  end if


! ********************************
! *** Initialize ensemble      ***
! ********************************

  inittype: if (type_ens_init==1) then

     ! *************************************************
     ! *** Initialize ensemble reading model outputs ***
     ! *************************************************

     ! allocate memory for temporary fields
     allocate(field(ny, nx))

     do member = 1, dim_ens
        if (member<10) then
           write (ensstr, '(i1)') member
        elseif (member<100) then
           write (ensstr, '(i2)') member
        elseif (member<1000) then
           write (ensstr, '(i3)') member
        end if

        do fid = 1, n_fields

           ! Read field
           open(11, file = '../inputs_online_2fields/ens'//trim(sfields(fid)%fname)//'_'//trim(ensstr)//'.txt', &
                status='old')

           ! Read global field
           do i = 1, ny
              read (11, *) field(i, :)
           end do

           ! +++ Note on counter s:
           ! +++ Using the counter s looks primitive, but it
           ! +++ makes the code fail-save because it avoids
           ! +++ index calculations involving nx_p or ny.

           ! Initialize process-local part of ensemble
           s = sfields(fid)%off
           do j = 1, nx_p
              do i = 1, ny
                 s = s + 1
                 ens_p(s, member) = field(i, nx_p*mype_model + j)
              end do
           end do
           
           close(11)
        end do
     end do

     deallocate(field)

  else inittype

     ! **************************************************
     ! *** Initialize ensemble from covariance matrix ***
     ! **************************************************

     ! allocate temporary arrays
     allocate(eofs(dim_p, dim_ens-1))
     allocate(svals(dim_ens-1))

     ! offset in x-direction due to domain-decomposition
     off_nx = nx_p*mype_filter


! *************************************************
! *** Initialize initial state and covar matrix ***
! *************************************************

     write(*,'(a,5x,a,a)') 'model-PDAF', '--- Read covariance information from ', trim(file_covar)

     call nfcheck( NF90_OPEN(file_covar, NF90_NOWRITE, fileid))

     ! Read rank stored in file
     call nfcheck( NF90_INQ_DIMID(fileid, 'rank', id_dim))
     call nfcheck( NF90_Inquire_dimension(fileid, id_dim, len=rank_file))

     do i = 1,  s
        if (stat(i) /= NF90_NOERR) &
             write(*, *) 'NetCDF error in reading dimensions from init file, no.', i
     end do

     ! Check consistency of dimensions
     checkdim: if (rank_file >= dim_ens-1) then

        ! Inquire IDs for mean state, singular vectors and values
        call nfcheck( NF90_INQ_VARID(fileid, 'sigma', id_svals))

        ! Read singular values
        startv(1) = 1
        countv(1) = dim_ens-1

        call nfcheck( NF90_GET_VAR(fileid, id_svals, svals, start=startv(1:1), count=countv(1:1)))

        ! Read mean state
        do fid = 1, n_fields
           call nfcheck( NF90_INQ_VARID(fileid, 'mean'//trim(sfields(fid)%fname), id_state))

           startv(2) = 1+off_nx
           countv(2) = nx_p
           startv(1) = 1
           countv(1) = ny

           call nfcheck( NF90_GET_VAR(fileid, id_state, &
                state_p(sfields(fid)%off+1 : sfields(fid)%off+sfields(fid)%dim), &
                start=startv(1:2), count=countv(1:2)))
        end do

        ! Read eofs
        do j = 1, dim_ens-1
           do fid = 1, n_fields
              call nfcheck( NF90_INQ_VARID(fileid, 'u_svd'//trim(sfields(fid)%fname), id_eofs))

              startv(3) = j
              countv(3) = 1
              startv(2) = 1+off_nx
              countv(2) = nx_p
              startv(1) = 1
              countv(1) = ny

              call nfcheck( NF90_GET_VAR(fileid, id_eofs, &
                   eofs(sfields(fid)%off+1 : sfields(fid)%off+sfields(fid)%dim, j), &
                   start=startv(1:3), count=countv(1:3)))
           end do
        end do

        call nfcheck( NF90_CLOSE(fileid))


! *****************************************
! *** Generate ensemble of model states ***
! *****************************************

        write (*,'(a, 5x, a)') 'model-PDAF', '--- generate state ensemble'
     
        ! Use PDAF routine to generate ensemble from covariance matrix
        call PDAF_SampleEns(dim_p, dim_ens, eofs, svals, state_p, ens_p, 1, flag)
     
     else

        ! *** Rank stored in file is smaller than requested EOF rank ***
        write(*,*) 'Rank stored in file is smaller than requested EOF rank'

        call nfcheck( NF90_CLOSE(fileid))
        call abort_parallel()

     end if checkdim

     deallocate(eofs, svals)

  end if inittype

end subroutine init_ens_pdaf_offline
