!>  Interface routine to call initialization of PDAF
!!
!! This routine collects the initialization of variables for PDAF.
!! In addition, the initialization routine PDAF_init is called
!! to perform the internal initialization of PDAF.
!!
!! This variant is for the online mode of PDAF.
!!
!! This routine is generic. However, it assumes a constant observation
!! error (rms_obs). Further, with parallelization the local state
!! dimension dim_state_p is used.
!!
!! __Revision history:__
!! * 2026-02 - Lars Nerger - Initial code for advanced tutorial revising tutorial case
!! * Later revisions - see repository log
!!
subroutine init_pdaf_offline()

  use model_pdaf_mod, &                ! Model variables
       only: nx_p, ny, n_dim, coords_x_p, coords_y_p
  use PDAF, &                          ! PDAF
       only: PDAF3_init, PDAF_set_iparam, &
       PDAFomi_set_domain_limits
  use parallel_pdaf_mod, &             ! Parallelization variables
       only: mype_ens, mype_filter, n_modeltasks, &
       abort_parallel
  use assimilation_pdaf_mod, &         ! Variables for assimilation
       only: dim_state_p, dim_state, dim_ens, &
       screen, filtertype, subtype, &
       delt_obs, step_offline, type_iau, steps_iau, &
       type_forget, forget, &
       locweight, cradius, sradius, coords_p, &
       type_trans, type_sqrt, &
       observe_ens, type_obs_init, &
       type_ens_init, file_covar
  use statevector_pdaf_mod, &          ! State vector variables and init routine
       only: setup_statevector, n_fields
  use io_pdaf_mod, &                   ! File input/output control
       only: write_state, write_ens, write_var
  use obs_A_pdafomi, &                 ! Variables for observation type A
       only: assim_A, rms_obs_A, file_obs_A
  use obs_B_pdafomi, &                 ! Variables for observation type B
       only: assim_B, rms_obs_B, file_obs_B

  implicit none

! *** Local variables ***
  integer :: i, j, k, s, off_nx        ! Counters
  integer :: pdaf_param_i(2)           ! Integer parameter array for filter
  real    :: pdaf_param_r(1)           ! Real parameter array for filter
  integer :: status_pdaf               ! PDAF status flag
  real    :: lim_coords(2,2)           ! limiting coordinates of process sub-domain

! *** External subroutines ***
  external :: init_ens_pdaf_offline    ! Ensemble initialization
  external :: next_observation_pdaf, & ! Provide time step of next observation
       distribute_state_pdaf, &        ! Routine to distribute a state vector to model fields
       prepoststep_pdaf                ! User supplied pre/poststep routine
  

! ***************************
! ***   Initialize PDAF   ***
! ***************************

  if (mype_ens == 0) then
     write (*,'(/a,1x,a)') 'model-PDAF', 'INITIALIZE PDAF - ONLINE MODE'
  end if


! **********************************************************
! ***   CONTROL OF PDAF - used in call to PDAF_init      ***
! **********************************************************

! *** IO options ***
  screen = 2              ! Write screen output (1) for output, (2) add timings
  write_state = .true.    ! Write ensemble mean fields
  write_ens = .true.      ! Write all ensemble states
  write_var = .false.     ! Write ensemble variance fields

! *** Ensemble settings ***
  dim_ens = n_modeltasks  ! Size of ensemble
                          !   We use n_modeltasks here, initialized in init_parallel_pdaf
  type_ens_init = 1       ! Type of ensemble initialization
  file_covar = '../generate_covar/covar.nc'  ! Path and name of covairance matrix file
                                             ! (generated by program generate_covar)

! *** Options for DA method

  ! ++++++++++++++++++++++++++++++++++++++++++++++++++
  ! +++ For available options see MOD_ASSIMILATION +++
  ! ++++++++++++++++++++++++++++++++++++++++++++++++++

  filtertype = 6     ! Type of filter
  subtype = 0        ! Subtype of filter

  forget  = 1.0      ! Forgetting factor value for inflation
  type_forget = 0    ! Type of forgetting factor

  type_trans = 0     ! Type of ensemble transformation (deterministic or random)
  type_sqrt = 0      ! SEIK/LSEIK/ESTKF/LESTKF: Type of transform matrix square-root


! *********************************************************************
! ***   Settings for analysis steps  - used in call-back routines   ***
! *********************************************************************

! *** Model time step to process
  step_offline = 1

! *** Forecast length (time interval between analysis steps) ***
  delt_obs = 2       ! This should be set according to the data availability

! *** Whether to initialize observation before prepoststep
  type_obs_init = 0  ! (0) before, (1) after

! *** Which observation type to assimilate
  assim_A = .true.
  assim_B = .false.

! *** specifications for observations ***
  rms_obs_A = 0.5    ! Observation error standard deviation for observation A
  rms_obs_B = 0.25   ! Observation error standard deviation for observation B

  file_obs_A = '../inputs_2fields/obsA.nc'  ! Observation file A
  file_obs_B = '../inputs_2fields/obsB.nc'  ! Observation file B

! *** Localization settings
  locweight = 2      ! Type of localizating weighting
  cradius = 5.0      ! Cut-off radius in local filters (in units of model coordinate)
  sradius = cradius  ! Support radius for 5th-order polynomial
                     ! or radius for 1/e for exponential weighting


! ***********************************
! *** Some optional functionality ***
! ***********************************

! *** Parse command line options
! *** This is optional, but useful
! *** One could also use a namelist file
  call init_pdaf_parse()


! ***************************
! *** Define state vector ***
! ***************************

  call setup_statevector(dim_state, dim_state_p, screen)


! *****************************************************
! *** Call PDAF initialization routine (all procs)  ***
! ***                                               ***
! *** For all filters, PDAF_init is first called    ***
! *** specifying only the required parameters.      ***
! *** Further settings are done afterwards using    ***
! *** calls to PDAF_set_iparam & PDAF_set_rparam.   ***
! *****************************************************

  ! *** Here we specify only the required integer and real parameters
  ! *** Other parameters are set using calls to PDAF_set_iparam/PDAF_set_rparam
  pdaf_param_i(1) = dim_state_p ! State dimension
  pdaf_param_i(2) = dim_ens     ! Size of ensemble
  pdaf_param_r(1) = forget      ! Forgetting factor

  call PDAF3_init(filtertype, subtype, step_offline, &
       pdaf_param_i, 2,&
       pdaf_param_r, 1, &
       init_ens_pdaf_offline, screen, status_pdaf)

  ! *** Additional parameter specifications ***
  ! *** -- These are all optional --        ***

  ! Generic settings
  call PDAF_set_iparam(5, type_forget, status_pdaf)      ! Type of forgetting factor
  call PDAF_set_iparam(6, type_trans, status_pdaf)       ! Type of ensemble transformation
  call PDAF_set_iparam(7, type_sqrt, status_pdaf)        ! Type of transform square-root (SEIK-sub4/ESTKF)
  call PDAF_set_iparam(8, observe_ens, status_pdaf)      ! Whether to apply observation operator to ensemble mean
  call PDAF_set_iparam(9, type_obs_init, status_pdaf)    ! Initialize observation before or after call to prepoststep


! *** Check whether initialization of PDAF was successful ***
  if (status_pdaf /= 0) then
     write (*,'(/1x,a6,i3,a43,i4,a1/)') &
          'ERROR ', status_pdaf, &
          ' in initialization of PDAF - stopping! (Process ', mype_ens,')'
     call abort_parallel()
  end if


! ***************************************************
! *** Set coordinates of elements in state vector ***
! *** (used for localization in EnKF/ENSRF)       ***
! ***************************************************

  allocate(coords_p(n_dim, dim_state_p))

  ! For localization in EnKF and EnSRF/EAKF, PDAFomi_set_localize_covar
  ! is called in the observation modules. This routine requires a 
  ! coordinate array corresponding to the state vector.

  s = 0
  do k = 1, n_fields
     do i = 1, nx_p
        do j = 1, ny
           s = s + 1
           coords_p(1, s) = coords_x_p(i)
           coords_p(2, s) = coords_y_p(j)
        end do
     end do
  end do


! ************************************************************************
! *** Set domain coordinate limits (for use with OMI's use_global_obs) ***
! ************************************************************************
  
  ! Get offset of local domain in global domain in x-direction
  off_nx = nx_p*mype_filter

  lim_coords(1,1) = real(off_nx + 1)     ! West
  lim_coords(1,2) = real(off_nx + nx_p)  ! East
  lim_coords(2,1) = real(ny)             ! North
  lim_coords(2,2) = 1.0                  ! South

  call PDAFomi_set_domain_limits(lim_coords)

end subroutine init_pdaf_offline
