!> Compute covariance matrix from state trajectory
!!
!! This programm to computes a covariance matrix from a
!! model trajectory. The matrix is decomposed in EOFs
!! and stored in form of eigenvalues and eigenvectors.
!! For the eigenvectors each model field is stored
!! separately.
!!
!! The matrix is generated by a singular value decomposition
!! of the perturbation matrix of a long state trajectory
!! about its time mean.
!!
!! __Revision history:__
!! * 2026-02 - Lars Nerger - Initial code based on code for L96
!! * Later revisions - see repository log
!!
program generate_covar

! !USES:
  use netcdf
  use PDAF
  use assimilation_pdaf_mod, &    ! Dimensions
       only: dim_state, dim_state_p, screen
  use model_pdaf_mod, &
       only: nx, ny
  use parallel_pdaf_mod
  use initialize_grid_mod, &
       only: initialize_grid
  use statevector_pdaf_mod, &
       only: setup_statevector, id, sfields, n_fields
  use parser, &                   ! Command line parser
       only: parse

  implicit none
  
! *** Local variables ***
  integer :: i, j, k, s, step, iter, member, maxtimes, rank      !< Counters
  character(len=120) :: inpath, outpath         !< File paths
  character(len=120) :: infile, outfile         !< File names
  character(len=150) :: file_in, ncfile_out   !< File name including path
  character(len=150) :: attstr                  !< Attribute string for NC (NetCDF) output
  integer :: ncid_in, ncid_out                  !< NC file IDs
  integer :: id_dim, id_time, id_state          !< NC dimension and variable IDs
  integer :: id_mean, id_sigma, id_svec         !< NC dimension and variable IDs
  integer :: dimid_rank, dimid_state, dimid_one !< NC dimension and variable IDs
  integer :: steps
!, dim_state                   ! Dimensions
  integer :: stat(100)                          !< Status for NC operations
  integer :: countv(3), startv(3)               !< Vectors for NC operations
  integer :: dimids(3)                          !< Vector for NC operations
  real :: limit                                 !< Lower limit for singular values
  real, allocatable :: times(:)                 !< Array of times from NC file
  real, allocatable :: field(:, :)              !< array to hold a single mdoel field
  real, allocatable :: states(:, :)             !< State trajectory
  real, allocatable :: meanstate(:)             !< Mean state of trajectory
  integer :: status                             !< Status Flag
  real,allocatable,dimension(:) :: svals        !< field of singular values
  real,allocatable,dimension(:,:) :: svdU       !< left singular vectors
  character(len=32) :: handle         ! Handle for command line parser
  character(len=32) :: stepstr         ! String for time step
  integer :: fid
  integer, allocatable :: id_means(:)
  integer, allocatable :: ids_svec(:)
  integer :: dimid_x, dimid_y

  ! Controls for PDAF_eofcovar
  integer :: remove_mean  !< (1) Let PDAF_eofcovar compute and subtract the mean state;
                          !< (0) mean already removed from trajectory
  integer :: do_mv        !< (1) to perform multivariate normalization; (0) no normalization

  ! Unused, but required variables for PDAF_eofcovar
  integer :: nfields        !< Number of fields
  integer :: dim_fields(1)  !< Size of field (only for multivariate scaling (not used here))
  integer :: offsets(1)     !< Offset of fields (only for multivariate scaling (not used here))
  real :: stddev(1)         !< STDDEV of field (only for multivariate scaling (not used here))


! **********************
! *** Initialize MPI ***
! **********************

  call init_parallel() ! initializes MPI
  
! *** Initialize MPI communicators for PDAF (model and filter) ***
! *** NOTE: It is always n_modeltasks=1 for offline mode       ***

  call init_parallel_pdaf(screen)


! ************************************************
! *** Specify state vector and state dimension ***
! ************************************************

  ! Initialize dimension information for NEMO grid
  call initialize_grid()

  ! Define state vector
  call setup_statevector(dim_state, dim_state_p, screen)


! ************************************************
! *** Configuration                            ***
! ************************************************

  ! Maximum number if time slices to consider
  maxtimes = 1000000

  ! Path to and name of file holding model trajectory
  inpath = '../inputs_online_2fields/'
  infile = 'true'

  ! Path to and name of output file holding covariance matrix
  outpath = './'
  outfile = 'covar.nc'

  ! Lower limit for eigenvalue
  limit = 1.0e-12

  ! Set num of time step to read
  steps = 9

  handle = 'steps'
  call parse(handle, steps)

  handle = 'inpath'
  call parse(handle, inpath)

  handle = 'infile'
  call parse(handle, infile)

  handle = 'outpath'
  call parse(handle, outpath)

  handle = 'outfile'
  call parse(handle, outfile)


! ************************************************
! *** Init                                     ***
! ************************************************

! *** Initial Screen output ***
  initscreen: if (mype_world == 0) then
     write (*,'(/10x,a)') '*******************************************'
     write (*,'(10x,a)') '*             GENERATE_COVAR              *'
     write (*,'(10x,a)') '*                                         *'
     write (*,'(10x,a)') '*    Compute covariance matrix and mean   *'
     write (*,'(10x,a)') '*     state from a sequence of states.    *'
     write (*,'(10x,a)') '*                                         *'
     write (*,'(10x,a)') '*   Write covar matrix as scaled eigen-   *'
     write (*,'(10x,a)') '*    vectors and singular values into     *'
     write (*,'(10x,a)') '*              NetCDF file                *'
     write (*,'(10x,a/)') '*******************************************'

     if (npes_world > 1) then
        write (*, '(16x, a, i3, a/)') 'Running on ', npes_world, ' PEs'
     else
        write (*, '(16x, a/)') 'Running on 1 PE'
     end if
  end if initscreen

  write (*,*) 'Read trajectory from directory: ',trim(inpath)
 
  ncfile_out = trim(outpath)//trim(outfile)
  write (*,*) 'Write covariance matrix to file: ',trim(ncfile_out)


! ************************************************
! *** Open trajectory file and read dimensions ***
! ************************************************


  write (*,'(/1x,a)') 'Dimensions of experiment:'
  write (*,'(5x,1x,a,i10)') 'state dimension', dim_state
  write (*,'(11x,a,i10)')   'time steps', steps

  if (steps < maxtimes) then
     write (*,'(1x,a)') '!! Number of available time slices is smaller than maxtimes - resetting!'
     maxtimes = steps
  end if
  write (*,'(13x,a8,i10)') 'maxtimes', maxtimes


! ****************************
! *** Read trajectory data ***
! ****************************

  write (*,'(/1x,a)') '------- Read trajectory -------------'

  allocate(field(ny, nx))
  allocate(states(dim_state, maxtimes))
  allocate(meanstate(dim_state))

  read_files: do step = 1, maxtimes

     IF (step<10) then
        write (stepstr, '(i1)') step
     elseif (step<100) then
        write (stepstr, '(i2)') step
     elseif (step<1000) then
        write (stepstr, '(i3)') step
     end IF

     do fid = 1, n_fields

        ! Read field
        file_in = trim(inpath)//trim(infile)//trim(sfields(fid)%fname)//'_step'//trim(stepstr)//'.txt'
        write (*,*) 'read file ', trim(file_in)
        open(11, file = file_in, status='old')

       ! Read global field
        do i = 1, ny
           read (11, *) field(i, :)
        end do

       ! +++ Note on counter s:
       ! +++ Using the counter s looks primitive, but it
       ! +++ makes the code fail-save because it avoids
       ! +++ index calculations involving nx_p or ny.

       ! Initialize process-local part of ensemble
        s = sfields(fid)%off
        do j = 1, nx
           do i = 1, ny
              s = s + 1
              states(s, step) = field(i, nx*mype_model + j)
           end do
        end do

        close(11)

     end do

  end do read_files


! *********************************************************
! *** Singular value decomposition of covariance matrix ***
! ***                                                   ***
! *** The covariance matrix is given by the state       ***
! *** sequences X of k states as                        ***
! ***          -1    _     _ T        T                 ***
! *** P = (k-1)   (X-X) (X-X)  = U L U  (EVP)           ***
! ***                                                   ***
! *** Thus we compute the singular value decomposition  ***
! ***     _        T            -1    2  T              ***
! ***   X-X = U S V ;  P = (k-1)   U S  U               ***
! ***                                                   ***
! ***                         -1/2                      ***
! *** and we store U and (k-1)     S in a NetCDF file.  ***
! *********************************************************

  write (*,'(/1x,a)') '------- Compute covariance matrix decomposition -------------'

  ! PDAF_eofcovar should compute and subtract the mean state from Trajectory 
  ! before decomposition. Afterwards, it's added again.
  remove_mean = 1

  ! Set some variables only used for multivariate normalization - not here!
  nfields = 1      ! One field
  dim_fields = 40  ! Size of field
  offsets = 0      ! offset of field from beginning of vector
  do_mv = 0   ! For testing one cat set do_mv=1 to activate normalization
  ! Note: multivariate normalization can be useful if there are several fields
  !       with difference variances. Here, we only have one field

  ! Allocate arrays for singular values and vectors
  allocate(svals(maxtimes))
  allocate(svdU(dim_state, maxtimes))

  ! Call routine generating matrix decomposition
  call PDAF_eofcovar(dim_state, maxtimes, nfields, dim_fields, offsets, &
       remove_mean, do_mv, states, stddev, svals, svdU, meanstate, 1, status)


! *********************************************************
! *** Write mean state and decomposed covariance matrix ***
! *********************************************************

! *** Determine rank to write ***

  getlimit: do i = 1, maxtimes
     if (svals(i) >= limit) then
        rank = i
     else
        exit getlimit
     end if
  end do getlimit
  if (rank < maxtimes) then
     write (*,'(1x,a,i6,a,es10.2)') &
          'Use maximum of ', rank, ' eigenvectors due to eigenvalue-limit of ',limit
  end if
  if (rank == maxtimes) then
     rank = maxtimes - 1
     write (*,'(5x,a,i4)') '++ reset rank to ',rank
  end if

  write (*,'(5x,a)') 'Singular values: '
  do i = 1, rank
    write (*, '(10x, i4, es12.3)') i, svals(i)
  end do


  write (*,'(/1x,a)') '------- Write decomposed covariance matrix and mean state -------------'

  ! *** Initialize file
  s = 1
  stat(s) = NF90_CREATE(ncfile_out, 0, ncid_out) 

  attstr = 'Mean state, singular vectors and values of decomposed covariance matrix for Lorenz96'
  s = s + 1
  stat(s) = NF90_PUT_ATT(ncid_out, NF90_GLOBAL, 'title', trim(attstr)) 

  ! Define dimensions
  s = s + 1
  stat(s) = NF90_DEF_DIM(ncid_out, 'rank',  rank, dimid_rank)
  s = s + 1
  stat(s) = NF90_DEF_DIM(ncid_out, 'dim_state', dim_state, dimid_state)
  s = s + 1
  stat(s) = NF90_DEF_DIM(ncid_out, 'one',  1, dimid_one)
  s = s + 1
  stat(s) = NF90_DEF_DIM(ncid_out, 'dim_x', nx, dimid_x)
  s = s + 1
  stat(s) = NF90_DEF_DIM(ncid_out, 'dim_y', ny, dimid_y)

  ! Define variables
  s = s + 1
  stat(s) = NF90_DEF_VAR(ncid_out, 'sigma', NF90_DOUBLE, dimid_rank, Id_sigma)

  ! mean state

  ! Define a mean-state variable for each model field
  dimids(1) = dimid_y
  dimids(2) = dimid_x

  allocate(id_means(n_fields))
  do fid = 1, n_fields
     s = s + 1
     stat(s) = NF90_DEF_VAR(ncid_out, 'mean'//trim(sfields(fid)%fname), NF90_DOUBLE, dimids(1:2), id_means(fid))
  end do

  dimids(1) = DimId_state
  dimids(2) = dimid_one

  s = s + 1
  stat(s) = NF90_DEF_VAR(ncid_out, 'meanstate', NF90_DOUBLE, dimids(1:2), Id_mean)

  ! singular vectors
  dimids(1) = DimId_y
  dimids(2) = DimId_x
  dimids(3) = dimid_rank

  allocate(ids_svec(n_fields))
  do fid = 1, n_fields
     s = s + 1
     stat(s) = NF90_DEF_VAR(ncid_out, 'u_svd'//trim(sfields(fid)%fname), NF90_DOUBLE, dimids(1:3), ids_svec(fid))
  end do


  dimids(1) = DimId_state
  dimids(2) = dimid_rank

  s = s + 1
  stat(s) = NF90_DEF_VAR(ncid_out, 'u_svd', NF90_DOUBLE, dimids(1:2), Id_svec)

  ! End Define mode
  s = s + 1
  stat(s) = NF90_ENDDEF(ncid_out) 

  do i = 1,  s
     if (stat(i) /= NF90_NOERR) &
          write(*, *) 'NetCDF error in init of output file, no.', i
  end do

  ! Write singular values
  s = s + 1
  stat(s) = NF90_PUT_VAR(ncid_out, id_sigma, svals(1:rank))


  ! Write mean state

  do fid = 1, n_fields

     startv(2) = 1
     countv(2) = nx
     startv(1) = 1
     countv(1) = ny
     s = s + 1
     stat(s) = NF90_PUT_VAR(ncid_out, id_means(fid), &
          meanstate(sfields(fid)%off+1 : sfields(fid)%off+sfields(fid)%dim), &
          start=startv(1:2), count=countv(1:2))
  end do

  startv(2) = 1
  countv(2) = 1
  startv(1) = 1
  countv(1) = dim_state
  s = s + 1
  stat(s) = NF90_PUT_VAR(ncid_out, id_mean, meanstate, start=startv(1:2), count=countv(1:2))

  do i = 1,  s
     if (stat(i) /= NF90_NOERR) &
          write(*, *) 'NetCDF error in writing state to output file, no.', i
  end do


  ! *** Write singular vectors

  writevectors: do i = 1, rank

     do fid = 1, n_fields

        startv(3) = i
        countv(3) = 1
        startv(2) = 1
        countv(2) = nx
        startv(1) = 1
        countv(1) = ny
        s = s + 1
        stat(s) = NF90_PUT_VAR(ncid_out, ids_svec(fid), &
             svdU(sfields(fid)%off+1 : sfields(fid)%off+sfields(fid)%dim, i), &
             start=startv, count=countv)
     end do

    ! Write singular vector
     startv(2) = i
     countv(2) = 1
     startv(1) = 1
     countv(1) = dim_state
     s = 1
     stat(s) = NF90_PUT_VAR(ncid_out, id_svec, svdU(:,i), start=startv(1:2), count=countv(1:2))

     do k = 1,  s
        if (stat(k) /= NF90_NOERR) &
             write(*, *) 'NetCDF error in writing singular vectors, no.', i,' rank',i
     end do

  end do writevectors

  ! Close file
  s = 1
  stat(s) = NF90_CLOSE(ncid_out)

  do i = 1,  s
     if (stat(i) /= NF90_NOERR) &
          write(*, *) 'NetCDF error in singular vectors to output file, no.', i
  end do



! ********************
! *** Finishing up ***
! ********************

  deallocate(states, meanstate)
  deallocate(svals, svdU)

  write (*,'(/1x,a/)') '------- END -------------'

end program generate_covar

